# Generated by Django 4.1.7 on 2023-02-19 10:58

import django.contrib.auth.models
from django.db import migrations, models
import django_cassandra_engine.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
                'managed': False,
            },
            bases=(django_cassandra_engine.models.DjangoCassandraModel, models.Model),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
