# Generated by Django 4.1.7 on 2023-02-22 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thread',
            fields=[
            ],
        ),
        migrations.CreateModel(
            name='ThreadContent',
            fields=[
            ],
        ),
    ]
